knf:
    app:
        jwtExpirationMs: 76300000
        jwtSecret: knowledgeFactory
spring:
    data:
        mongodb:
            database: knfDemoDb
            host: localhost
            port: 27017